2021-01-20 10:12:35,920-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-20 10:14:08,274-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:15:18,596-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:16:18,708-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:16:24,025-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:16:29,847-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:18:07,636-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:19:17,437-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:20:14,956-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:20:20,350-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:20:26,132-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:55:31,449-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-20 10:57:24,436-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:58:34,995-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:59:32,332-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:59:37,639-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 10:59:45,819-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 11:00:00,332-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 11:00:05,700-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 11:01:45,879-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 11:03:04,950-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 11:04:04,490-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 11:04:09,723-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 11:04:17,889-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-20 11:04:32,434-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

